version: 0.2

phases:
  install:
    commands:
      - pip install -r ./requirements.txt
  pre_build:
    commands:
      - echo Running tests with pytest
      - python -m unittest tests/test_add_to_blacklist.py tests/test_check_blacklist.py
      - echo Tests executed successfully
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 593793065204.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t misw4304-g10/blacklist .
      - docker tag misw4304-g10/blacklist:latest 593793065204.dkr.ecr.us-east-2.amazonaws.com/misw4304-g10/blacklist:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 593793065204.dkr.ecr.us-east-2.amazonaws.com/misw4304-g10/blacklist:latest
artifacts:
  files:
    - '**/*'